version: '3.8'

services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: satisfacao_db
    networks:
      - app-network

  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - app-network

  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge